### ISSUE TITLE
Quando esta previsto o inicio das atividades de produção?

### ISSUE THREAD

**Issue by ogilvieira** [CursinhoTransFormacao/landing#1]
Oi! estou aguardando para participar, gostaria de algum esclarecimento se é uma atitude sólida e que realmente precisa de ajuda pois estou disposto e desde que me inscrevi para ajudar, não houve feedback de como posso colaborar. 

Obrigado!

**Comment by frenktico** [comment]
Gil,

Sim o projeto é uma atitude sólida, preciso sim de ajuda, no entanto como
sou freelancer preciso cuidar de algumas outras situações. No momento estou
estruturando o briefing para o site final, já que nesse momento será feita
apenas a landing page. Esse momento próximo da parada gay e outras
atividades internas tomaram meu tempo, mas já retorno e faço o que for
preciso para atualizar o repositório.

Atenciosamente

[image: --]

Francisco Franco
[image: https://]about.me/f.aldiney
https://about.me/f.aldiney?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links

Em 17 de maio de 2016 16:44, Gil Vieira notifications@github.com escreveu:

**Comment by frenktico** [comment]
@ogilvieira não sei se você viu, mas já iniciei a atualização do repositório e finalizei o layout da landing page.

**Comment by ogilvieira** [comment]
Estou clonando e vamos ver no que posso colaborar :D

**Comment by frenktico** [comment]
Gil,

Você está acompanhando pelo post do Facebook? Nele venho comentando algumas
das alterações realizadas também. Agora o foco está no CSS. Quando essa
etapa estiver finalizada pretendo partir para algumas "animações" via
jQuery ou JS e até transitions do CSS.

Qualquer dúvida só mandar mensagem aqui, no drive (briefing) ou pelo Github
mesmo. ​Estou focando em finalizar no máximo sexta da semana que vem tudo.​

_​Briefing_
https://docs.google.com/document/d/1mdpj7h3pmtt9TRYUogGyuKRCPEUSP9IN_9srDP4h-pU

_Post Facebook_
​
https://www.facebook.com/groups/free.code.camp.sao.paulo/permalink/270593329941985

​Abraço

[image: --]

Francisco Franco
[image: https://]about.me/f.aldiney
https://about.me/f.aldiney?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links

2016-06-17 11:04 GMT-03:00 Gil Vieira notifications@github.com:

**Comment by frenktico** [comment]
#outlook a {

padding: 0;
}
.ReadMsgBody {

width: 100%;
}
.ExternalClass {

width: 100%;
}
.ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {

line-height: 100%;
}
body, table, td, a {

-webkit-text-size-adjust: 100%;

-ms-text-size-adjust: 100%;
}
table, td {

mso-table-lspace: 0pt;

mso-table-rspace: 0pt;
}
img {

-ms-interpolation-mode: bicubic;
}

body {

margin: 0;

padding: 0;

}
img {

border: 0;

height: auto;

line-height: 100%;

outline: none;

text-decoration: none;
}
table {

border-collapse: collapse !important;
}
body {

height: 100% !important;

margin: 0;

padding: 0;

width: 100% !important;
}

appleBody a {

color: #68440a;

text-decoration: none;
}
.appleFooter a {

color: #999999;

text-decoration: none;
}
.faq {

line-height: 18px;

list-style: outside none none;

margin: 10px 0;

padding: 0;
}
.mobile-only {

display: none;
}

@media screen and (max-width: 525px) {

table[class="wrapper"] {

width: 100% !important;
}

td[class="logo"] {

text-align: left;

padding: 20px 0 20px 0 !important;
}
td[class="logo"] img {

margin: 0 auto!important;
}

[class="mobile-only"] {

display: block;
}

br[class="mobile-hide"] {

display: none;
}
td[class="mobile-hide"] {

display: none;
}
img[class="mobile-hide"] {

display: none !important;
}
img[class="img-max"] {

max-width: 100% !important;

width: 100% !important;

height: auto !important;
}

img[class="img-min"] {

max-width: 73px !important;

width: 73px !important;

height: auto !important;

padding-top: 8px !important;
}

img[class="img-apps"] {

max-width: 46% !important;

width: 46% !important;

height: auto !important;
}
img[class="img-max-profile"] {

max-width: 50% !important;

width: 50% !important;

height: auto !important;

border-radius: 200px;
}

table[class="responsive-table"] {

width: 100%!important;
}

td[class="padding"] {

padding: 10px 5% 15px 5% !important;
}
td[class="amount"] {

font-size: 10px!important;
}
td[class="mobile-text-twelve"] {

font-size: 12px!important;
}
span[class="mobile-text-twelve"] {

font-size: 14px!important;
}
td[class="padding-copy"] {

padding: 10px 5% 10px 5% !important;

text-align: center;
}
td[class="padding-meta"] {

padding: 30px 5% 0px 5% !important;

text-align: center;
}
td[class="no-pad"] {

padding: 0 0 20px 0 !important;
}
td[class="no-pad-bottom"] {

padding: 25px 0 0 0 !important;
}
td[class="no-padding"] {

padding: 0 !important;
}
td[class="section-padding"] {

padding: 25px 15px 25px 15px !important;
}
td[class="section-no-padding-bottom"] {

padding: 25px 15px 0 15px !important;
}

td[class="section-no-padding-top"] {

padding: 0 5% 25px 5% !important;
}

td[class="section-no-padding-top-bottom"] {

padding: 0 5% 0 5% !important;
}
td[class="section-padding-bottom-image"] {

padding: 50px 15px 0 15px !important;
}

td[class="mobile-wrapper"] {

padding: 10px 5% 15px 5% !important;
}
table[class="mobile-button-container"] {

margin: 0 auto;

width: 100% !important;
}
a[class="mobile-button"] {

width: 80% !important;

padding: 15px !important;

border: 0 !important;

font-size: 16px !important;
}
}

Francisco Franco sent you $20 to try the all-new empowr:

Receive your $20 &#9658;

Your empowr account was reserved for you by francisco.aldiney@gmail.com in order to store your gift however you must agree to terms and validate before it can be created.

By accessing your account via the links or buttons in this email, you're both validating your email and stipulating that you're 18 or older and are signing up having agreed with the product, terms and privacy policies, including the manner in which "$", "earnings", maturation and advertising are used or applied throughout the empowr products and communications.

Earnings are virtual currency revenues, not profits; are for illustrative purposes only and are in no way a guarantee of anything.

While your account is very new, if you fail to sign in for just a few days, it will be deleted to eliminate unwanted emails for you, so click a button in emails periodically to notify the system of your desire to keep it active. You can manually delete your account and/or block future invitations from here
http://profile.empowr.com/ApplicationManager/CommunityEmailSettings.aspx?em=K%2FzdUVCDppRPZBZ7QTSdr7bnnXXQU2MpWFBAKKi63VmcVr4%2BqFvVIGuhiMyChmWsWMIGiYPSCTIWh71QxhtJvCmWHkfEf%2BEGaZ9nYTjN3Xpqxut4ICaagaotTPmOXkFmkUUGs0l7IVIZWCdTgzlQ5eIpbNohgrCv&vet=694&mlid=9392323757&fn=6k5SCVt9Pc4id0iKIt3pyg%3D%3D.

No more emails from Francisco Franco (francisco.aldiney@gmail.com)? Unsubscribe
http://profile.empowr.com/ApplicationManager/CommunityEmailSettings.aspx?em=K%2FzdUVCDppRPZBZ7QTSdr7bnnXXQU2MpWFBAKKi63VmcVr4%2BqFvVIGuhiMyChmWsWMIGiYPSCTIWh71QxhtJvCmWHkfEf%2BEGaZ9nYTjN3Xpqxut4ICaagaotTPmOXkFmkUUGs0l7IVIZWCdTgzlQ5eIpbNohgrCv&vet=694&mlid=9392323757&fn=6k5SCVt9Pc4id0iKIt3pyg%3D%3D

*This promotional email has been sent by francisco.aldiney@gmail.com to reply@reply.github.com. You can prevent future emails here. empowr - 501 West Broadway, Suite A182, San Diego, CA 92101, USA

**Comment by frenktico** [comment]
#outlook a {

padding: 0;
}
.ReadMsgBody {

width: 100%;
}
.ExternalClass {

width: 100%;
}
.ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {

line-height: 100%;
}
body, table, td, a {

-webkit-text-size-adjust: 100%;

-ms-text-size-adjust: 100%;
}
table, td {

mso-table-lspace: 0pt;

mso-table-rspace: 0pt;
}
img {

-ms-interpolation-mode: bicubic;
}

body {

margin: 0;

padding: 0;

}
img {

border: 0;

height: auto;

line-height: 100%;

outline: none;

text-decoration: none;
}
table {

border-collapse: collapse !important;
}
body {

height: 100% !important;

margin: 0;

padding: 0;

width: 100% !important;
}

appleBody a {

color: #68440a;

text-decoration: none;
}
.appleFooter a {

color: #999999;

text-decoration: none;
}
.faq {

line-height: 18px;

list-style: outside none none;

margin: 10px 0;

padding: 0;
}
.mobile-only {

display: none;
}

@media screen and (max-width: 525px) {

table[class="wrapper"] {

width: 100% !important;
}

td[class="logo"] {

text-align: left;

padding: 20px 0 20px 0 !important;
}
td[class="logo"] img {

margin: 0 auto!important;
}

[class="mobile-only"] {

display: block;
}

br[class="mobile-hide"] {

display: none;
}
td[class="mobile-hide"] {

display: none;
}
img[class="mobile-hide"] {

display: none !important;
}
img[class="img-max"] {

max-width: 100% !important;

width: 100% !important;

height: auto !important;
}

img[class="img-min"] {

max-width: 73px !important;

width: 73px !important;

height: auto !important;

padding-top: 8px !important;
}

img[class="img-apps"] {

max-width: 46% !important;

width: 46% !important;

height: auto !important;
}
img[class="img-max-profile"] {

max-width: 50% !important;

width: 50% !important;

height: auto !important;

border-radius: 200px;
}

table[class="responsive-table"] {

width: 100%!important;
}

td[class="padding"] {

padding: 10px 5% 15px 5% !important;
}
td[class="amount"] {

font-size: 10px!important;
}
td[class="mobile-text-twelve"] {

font-size: 12px!important;
}
span[class="mobile-text-twelve"] {

font-size: 14px!important;
}
td[class="padding-copy"] {

padding: 10px 5% 10px 5% !important;

text-align: center;
}
td[class="padding-meta"] {

padding: 30px 5% 0px 5% !important;

text-align: center;
}
td[class="no-pad"] {

padding: 0 0 20px 0 !important;
}
td[class="no-pad-bottom"] {

padding: 25px 0 0 0 !important;
}
td[class="no-padding"] {

padding: 0 !important;
}
td[class="section-padding"] {

padding: 25px 15px 25px 15px !important;
}
td[class="section-no-padding-bottom"] {

padding: 25px 15px 0 15px !important;
}

td[class="section-no-padding-top"] {

padding: 0 5% 25px 5% !important;
}

td[class="section-no-padding-top-bottom"] {

padding: 0 5% 0 5% !important;
}
td[class="section-padding-bottom-image"] {

padding: 50px 15px 0 15px !important;
}

td[class="mobile-wrapper"] {

padding: 10px 5% 15px 5% !important;
}
table[class="mobile-button-container"] {

margin: 0 auto;

width: 100% !important;
}
a[class="mobile-button"] {

width: 80% !important;

padding: 15px !important;

border: 0 !important;

font-size: 16px !important;
}
}

Yesterday, Francisco Franco sent you $20 to try the all-new empowr:

Receive your $20 &#9658;

Your empowr account was reserved for you by francisco.aldiney@gmail.com in order to store your gift however you must agree to terms and validate before it can be created.

By accessing your account via the links or buttons in this email, you're both validating your email and stipulating that you're 18 or older and are signing up having agreed with the product, terms and privacy policies, including the manner in which "$", "earnings", maturation and advertising are used or applied throughout the empowr products and communications.

Earnings are virtual currency revenues, not profits; are for illustrative purposes only and are in no way a guarantee of anything.

While your account is very new, if you fail to sign in for just a few days, it will be deleted to eliminate unwanted emails for you, so click a button in emails periodically to notify the system of your desire to keep it active. You can manually delete your account and/or block future invitations from here
http://profile.empowr.com/ApplicationManager/CommunityEmailSettings.aspx?em=K%2FzdUVCDppRPZBZ7QTSdr7bnnXXQU2MpWFBAKKi63VmcVr4%2BqFvVIGuhiMyChmWsWMIGiYPSCTIWh71QxhtJvCmWHkfEf%2BEGaZ9nYTjN3Xpqxut4ICaagaotTPmOXkFmkUUGs0l7IVIZWCdTgzlQ5eIpbNohgrCv&vet=694&mlid=9396775241&fn=6k5SCVt9Pc4id0iKIt3pyg%3D%3D.

No more emails from Francisco Franco (francisco.aldiney@gmail.com)? Unsubscribe
http://profile.empowr.com/ApplicationManager/CommunityEmailSettings.aspx?em=K%2FzdUVCDppRPZBZ7QTSdr7bnnXXQU2MpWFBAKKi63VmcVr4%2BqFvVIGuhiMyChmWsWMIGiYPSCTIWh71QxhtJvCmWHkfEf%2BEGaZ9nYTjN3Xpqxut4ICaagaotTPmOXkFmkUUGs0l7IVIZWCdTgzlQ5eIpbNohgrCv&vet=694&mlid=9396775241&fn=6k5SCVt9Pc4id0iKIt3pyg%3D%3D

*This promotional email has been sent by francisco.aldiney@gmail.com to reply@reply.github.com. You can prevent future emails here. empowr - 501 West Broadway, Suite A182, San Diego, CA 92101, USA

**Comment by frenktico** [comment]
body { margin:0 !important; }
div[style*="margin: 16px 0"] { margin:0 !important; font-size:100% !important; }
#outlook a {

padding: 0;
}
ReadMsgBody {

width: 100%;
}
ExternalClass {

width: 100%;
}
ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {

line-height: 100%;
}
body, table, td, a {

-webkit-text-size-adjust: 100%;

-ms-text-size-adjust: 100%;
}
table, td {

mso-table-lspace: 0pt;

mso-table-rspace: 0pt;
}
img {

-ms-interpolation-mode: bicubic;
}

body {margin: 0;padding: 0;}
img {

border: 0;

height: auto;

line-height: 100%;

outline: none;

text-decoration: none;
}
table {

border-collapse: collapse !important;
}
body {

height: 100% !important;

margin: 0;

padding: 0;

width: 100% !important;
}

appleBody a {

color: #68440a;

text-decoration: none;
}
appleFooter a {

color: #999999;

text-decoration: none;
}
faq {

line-height: 18px;

list-style: outside none none;

margin: 10px 0;

padding: 0;
}
mobile-only {

display: none;
}
img-apps { padding:0 5px 0 0;}

a.mobile-button:link, a.mobile-button:visited { color:#fff!important;}

@media screen and (max-width: 525px) {

table[class="wrapper"] {

width: 100% !important;
}

td[class="logo"] {

text-align: left;

padding: 20px 0 20px 0 !important;
}
td[class="logo"] img {

margin: 0 auto!important;
}

[class="mobile-only"] {

display: block;
}

br[class="mobile-hide"] {

display: none;
}
td[class="mobile-hide"] {

display: none;
}
img[class="mobile-hide"] {

display: none !important;
}
img[class="img-max"] {

max-width: 100% !important;

width: 100% !important;

height: auto !important;
}

img[class="img-min"] {

max-width: 73px !important;

width: 73px !important;

height: auto !important;

padding-top: 8px !important;
}

img[class="img-apps"] {

max-width: 46% !important;

width: 46% !important;

height: auto !important;

padding:0 2px;
}
img[class="img-max-profile"] {

max-width: 50% !important;

width: 50% !important;

height: auto !important;

border-radius: 200px;
}

table[class="responsive-table"] {

width: 100%!important;
}

td[class="padding"] {

padding: 10px 5% 15px 5% !important;
}
td[class="amount"] {

font-size: 9px!important;
}
td[class="mobile-text-twelve"] {

font-size: 12px!important;
}
span[class="mobile-text-twelve"] {

font-size: 14px!important;
}
td[class="padding-copy"] {

padding: 10px 5% 10px 5% !important;

text-align: center;
}
td[class="padding-meta"] {

padding: 30px 5% 0px 5% !important;

text-align: center;
}
td[class="no-pad"] {

padding: 0 0 20px 0 !important;
}
td[class="no-pad-bottom"] {

padding: 25px 0 0 0 !important;
}
td[class="no-padding"] {

padding: 0 !important;
}
td[class="section-padding"] {

padding: 25px 15px 25px 15px !important;
}
td[class="section-no-padding-bottom"] {

padding: 25px 15px 0 15px !important;
}

td[class="section-no-padding-top"] {

padding: 0 5% 25px 5% !important;
}

td[class="section-no-padding-top-bottom"] {

padding: 0 5% 0 5% !important;
}
td[class="section-padding-bottom-image"] {

padding: 50px 15px 0 15px !important;
}

td[class="mobile-wrapper"] {

padding: 10px 5% 15px 5% !important;
}
table[class="mobile-button-container"] {

margin: 0 auto;

width: 100% !important;
}
a[class="mobile-button"] {

width: 80% !important;

padding: 15px !important;

border: 0 !important;

font-size: 16px !important;
}
}

has invited you to this exclusive free trial
http://www.empowr.com/Navigation/RegistrationWelcome.aspx?Action=ReferralInstantRegistration&amp;RegistrationFlowFlavor=7&amp;authToken=tejupZWgK91nFrxTrfTol%2f4aAqys%2b5WoCDewaKDGyOlox8UgsSixz3epY7oEfMXT8yZEcj5rqp%2beCwISxUZLwvTyzbDxAOmON1VaT5u%2f1YtMbtuPjbCit%2bQ%2ffTPj%2fXJp4WAQu5w9u%2fnhfvzIywSVIPQb5haI1YQlD1hIEMWHadORtjHVqJL%2b8hoUtIpcwscsow5YETvXrnLGJcbAm7iUguEBk84JPqOWDr%2bwQ3R5HqkRbP%2f0q6YdnC%2fNqnhEwdsNVjJkyU2KNL7JFUIgsv%2b2pdEwDnIEoaeWAlgz0vOC4BEdPfrdcBRNs6p4cmGTi%2bv2&amp;PolicyAcceptance=8OZYoFAq%2fTwyV9yibgSP1VXTB7npxf%2bDI6%2fL7EaBF%2fre%2fJPVjrLivNWXGjXe9wx3OoE7OJBURTKwNoMeZQzNPrcFX%2bGrvUYF96OXrBK6xmmggPevFadfje0CAgaXp%2f%2br9HE7byZEtBZLYYo%2fFNWhZtTNkKXwV0kAF5EW4Aqb65ekrYDVCQG7FxdccvqOA%2bpavuw%2foLk21YQr5U7sLZ3I%2fvcZAEFCbLFo6heLvZbIDS451%2fvXrzTOUu43Yuml5iIwaFmYhWELZPP%2bMJ5UeQxQRzp6Hz7xT3tcHuyLKyKWMHSzcHzWkpl5ym8i11ErRz6r1jGX3TctolpVrpBTivWSXj7Wc53FzxgGJKKlBMHO24Tt6tru0p09aSpAgCY5YH0YCDOnX75p4PcWeq3DuWdT94QJEV1qU9HlfQMSrlkcl%2foSYruVH%2bZSrnKTINCfKmW%2fmaBACRyAjbjQRyerKrQ4nT005Pzb4IJfQBxV89T8FZpj%2b7BcwYN9AYCfM1bXQedrhod8xXPxv5e1QeVyFr4jzZ2nVc94UALToo2WA5QAteqyWWVxBmcORK8AW5brNoXOD1zFXc3MNLeixqS5bOiPoHWnixW08cs%2f4rlCfL8qunp0pzM4%2fS6uo88saqiWo3NQxGcXwG74XRkXjvdBb8hVRq3nR7Q1rDF3c4cInfZHeEUG%2fhX6Lal1CMaCd4MUIytKEMhGylDY9dCYsE%2b0NXWAFMgN8muqTA1cLY4tAcDPWHsZZs06MuSTwhRH2F90otdi%2fZTDjfhchVXOIv1nI0zNiadu9S9vHYLMQl82vGpDWJYhigR02EafJHwYrU8dEl%2bh7xnTmxsgb5rkFfxC1CLczFQtETKQFXpPoDuMQ%2fW3ZZ8QzYWIFbnijkDUE0PMKp1B7FPQgmdyipz%2bd8fJfGMjbYr%2b4AV2zpchCeOYkVxwcxQvxHe2g1MP9JsP%2fCkcNCiVD919OJUJD%2faCugFqHD4EhyOl5omCVVRDLSpDB7s0Dns%3d&amp;vet=745&amp;dt=081017&amp;mlid=9859002259&amp;tmpID=3340&amp;linkname=InviteLink&amp;pt=0&amp;esp=0&amp;eaid=62798260&amp;rt=1:

Your account was reserved for you by  in order to reserve your free trial, however you must agree to terms and validate before it can be created.

By accessing your account via the links or buttons in this email, you're both validating your email and stipulating that you're 18 or older and are signing up having agreed with the product, terms and privacy policies, including the manner in which "$", "earnings", maturation and advertising are used or applied throughout the empowr products and communications.

Earnings are virtual currency revenues, not profits; are for illustrative purposes only and are in no way a guarantee of anything. You can manually delete your account and/or block future invitations from here
http://profile.empowr.com/ApplicationManager/CommunityEmailSettings.aspx?em=K%2FzdUVCDppRPZBZ7QTSdr7bnnXXQU2MpWFBAKKi63VmcVr4%2BqFvVIGuhiMyChmWsWMIGiYPSCTIWh71QxhtJvCmWHkfEf%2BEGaZ9nYTjN3Xpqxut4ICaagaotTPmOXkFmkUUGs0l7IVIZWCdTgzlQ5eIpbNohgrCv&vet=745&mlid=9859002259.

No more emails from  ()? Unsubscribe
http://profile.empowr.com/ApplicationManager/CommunityEmailSettings.aspx?em=K%2FzdUVCDppRPZBZ7QTSdr7bnnXXQU2MpWFBAKKi63VmcVr4%2BqFvVIGuhiMyChmWsWMIGiYPSCTIWh71QxhtJvCmWHkfEf%2BEGaZ9nYTjN3Xpqxut4ICaagaotTPmOXkFmkUUGs0l7IVIZWCdTgzlQ5eIpbNohgrCv&vet=745&mlid=9859002259

*This promotional email was sent to reply@reply.github.com and may contain special notices or offers. To see current terms and conditions visit: empowr Terms and Conditions. You can prevent future emails here. You can change your password here. empowr - 501 West Broadway, Suite A182, San Diego, CA 92101, USA

**Comment by frenktico** [comment]
body { -ms-text-size-adjust: none !important; font-family:'Helvetica Neue', Helvetica, Arial, sans-serif;}

My balance: $1,000

Home

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

p

small-text

Hello,

Starting in 2016, you were an early (alpha) member of our project called empowr. Well, that project evolved and became the new www.empowr.com. Along the way, we invented virtual currency and many other technologies used by all the top social media companies.

Your free coins

As you probably know by now, empowr is launching its own coin (like Bitcoin) and, as our way of saying Thank You to the incredible community that got us here, we're giving the first coins to you – TOTALLY FREE. Read the details
http://www.empowr.com/Navigation/RegistrationWelcome.aspx?Action=ReferralInstantRegistration&amp;RegistrationFlowFlavor=18&amp;authToken=6yU53RwHuZUbcai%2bCnPAvUXYqetPlF0zPLbuysbjEL0bIigvCqz9Me7XVxwWYMxAKkp9WYoi4%2fK2Nn7qg5RjVMhZi4BxlPvI7%2bKepj68VRSll48do%2beZm8CLHf4AwNRiiEpVRKnIvXFXf4zMgE1o9VoDadIDj69b0NsvnM6CkItox6N3uLTwkOfwG4mggJIJngUwdoRkDMt%2bNW0w%2fFukTALeW9Q6tzehCqiiTGvonWwc%2fmRvex7FMIV4%2f8xJoJcfWcrmmk%2fPceQo%2blQTrIVc2LgzZWlbHpL%2b2X%2fNc77aGKixlAgVcqWVATF9nR5q%2fY4b&amp;PolicyAcceptance=iniN0i00gi0xLZcSM9o%2bKZsR%2bxnAKAWcfHdkh0wLBrElT6FyjU7fxqLdWCdUR88ysW9EE21zaAzxUW%2bMI0uoqwpqPctxoxZd%2fQ%2fcGs7uyt0kcMDhheK%2bOiOuc%2bryFPwrmGOuF94lOh0ZAzvNaFK4Vi%2fYbz2uQ4FEZvIe6VQaBY3IucIVgiNRgnmu5EZx1QUIp7DWuGvFX0%2bXcizXHtfK7q%2fCB5yDdSIKZ0bZFTmZoicDWHVurUz6FUFO1nXq%2f85VIXiy9KAD3KwqpIAz7wsaokV800EtibEFGTI2yLUC7jkTIhsahnnM8%2btVxlUoTFSKmMQ6nXMNyXizmYxrXGqEIm8FkDZEDF%2fnSBLLO0TodeOnZXZflP6r4%2bZwembnsyGFyexPAfwX2Lb4UEJ%2fI1y4f6p8MMiNKxxqt94hAhtTqyTCqWwuJloLImLHDD4%2bJAyBWF0Ne9gdFtLIaO8Wqnt9OVhDYkrWTdiSCFnxMlGNf4EmHBMVcOjC%2b30kzmgI7mmz0r4g1KIH5nLdcIzZ%2bZPaGhoQ4DRCCh9%2bY3XlWDguz54GA2Y0RuMgliGefLfZlPaF13LCMYBWpV3SuZPE7okioefCGVSatETOSAVRdACQFbUgP%2b45e7TVJXmqVbS3j0SN1eMZrq2%2bjKN1BvI9I9v7HK7Vt8qerLfK5SWX7Pt5b7ew1rp0QwyUSlOhf3VPaDXJ3vIixV8p%2fWMfABZcV8lSTRmiNAKFvvsYayctndVeKgef0p%2bMUDJmArCsldiCs%2buJAPSOSjOSTs4VJtnntZSY80eJubP%2fmf2h37KrJ1eIIx8VMzBMeC7ILFPuYos1FTxEDebrcAdM4TR5j6ARS87GnUqW7d5%2fJMCkiqNHkyI2B6a0PBZzDhw4u5paYyDni4AXESQ50Z67HaSOPHsHSGatSEggLboZLR1VjSW0MKHr1nV%2b8VC%2fSdQg9nEk3ceZENMj3ICRXijzNAneXd7YQuAARA%3d%3d&amp;vet=760&amp;dt=122917&amp;mlid=10115657079&amp;tmpID=3378&amp;linkname=InviteLink&amp;pt=0&amp;esp=0&amp;eaid=62798260&amp;rt=1

Secure your free coins &#9658;

Note: Unclaimed coins will be auctioned off to the rest of the community. (As an early member, you get exclusive first access to bid on any unclaimed coins).

Once again, THANK YOU.
-Your friends at empowr.com

Your account was reserved for you in order to allocate your free coins, however you must agree to terms and validate before it can be utilized. By accessing your account via the links or buttons in this email, you're both validating your email and stipulating that you're 18 or older and are signing up having agreed with the product, terms and privacy policies.

At this moment, empowr can make no guarantees about the current or future price or value of the new empowr cryptocurrency coin, or that it will be ultimately tradeable on one or more public currency exchanges. By accepting your free founder coins, you acknowledge that this offer represents a gift that can be revoked if it is found to not be legal in your state, country or jurisdiction. Vesting and other details apply.

You are receiving this gift and email because you were an alpha user of the SMS.ac / FanBox / empowr project. You can unsubscribe here
#.

-->

New! Download the empowr mobile app:

&nbsp;

&nbsp;

*This promotional email was sent to reply@reply.github.com and may contain special notices or offers. To see current terms and conditions visit: FanBox Terms and Conditions. You can prevent future emails here.
FanBox - 611 K Street, Suite B411, San Diego, CA 92101, USA

**Comment by frenktico** [comment]
body { -ms-text-size-adjust: none !important; font-family:'Helvetica Neue', Helvetica, Arial, sans-serif;}

My balance: $1,000

Home

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

p

small-text

Hello,

Starting in 2016, you were an early (alpha) member of our project called empowr. Well, that project evolved and became the new www.empowr.com. Along the way, we invented virtual currency and many other technologies used by all the top social media companies.

Your free coins

As you probably know by now, empowr is launching its own coin (like Bitcoin) and, as our way of saying Thank You to the incredible community that got us here, we're giving the first coins to you – TOTALLY FREE. Read the details
http://www.empowr.com/Navigation/RegistrationWelcome.aspx?Action=ReferralInstantRegistration&amp;RegistrationFlowFlavor=18&amp;authToken=5Ttj96tfB1VoFNFSLjIEYmsmQICnQ%2f1YH7CwE2QjM1MwsFoPHfh5GNhiHmla2XC%2b%2fAZSbdJc8RveEV3216j8PDUMjZ4mSr9knHqkybKH%2btY6f2rtVq%2fMnaNOI6Zz0o4pgCfSuz1gpGzaAYfstd4vzgUKORmEzABm7DWfwm6mpJlYoFAgT5hlOVE6wcUXf8M8mQPCGKAK69gd1Py9ffOAz8Lr0gqX0gae3z7cLQjOBFrkS8KNou2wGJImvYdkrE3A9gEg%2bTKI75ogk3phdPh5Eml5vq1CprUGbBus%2fr1xozfXC3Fl5MiaverPYT33KoRO&amp;PolicyAcceptance=XXIsgdm%2fgu7D5%2fkcAHEqNy%2bMMedJE3Mu%2fxw4MaLv5nQRhCQEZ2Oij7odXiJ2M6%2fuRiEyx4%2fbCplcQRlpUueT0EGyCfDOefZay%2by9k5jPHyIHg0eCX2ACol%2bB1UOCBB%2bed50XWxG3sB7S2JTGRm9EBIs0xkFttglyoWN4RQKB4QB55bMaWnC0NQhj02kT3tczQqFMS8wMsXOaM3glfYMf4aLXB2WsvCezPQmfDlSB6o5PIrXUkx61EswIlng5AmP6VRaW2BURIn0%2flAuIAFQAwYdoHMLGPd0pTUwk5UresTGIDJyrtto7eQOGFpgchIwmYgOEg%2b%2bc45F%2f5x7BtgQea1kJs1xgUSw%2bQ0%2bGfZgncrH3ljlPdrLyxwirgjq3Bfno7R%2bq249MyAokhYpTnbvtqkMA6Jo65CoHHj7bIr5ONg0EuaGyYFQeihPJwnADIgfd8MGK5ZO%2fmf3WtSy0dTPV3VG3Xxb21cMkaLssA32bbMjQO08vhFoMAgJmug%2bd957J7JXIQcGk1bxazzH3gMSNdh%2bZMRxrGEGfhnU06KxQs%2fu3zfrDGqbS0ak0Imbg9leilh0uNKWvtzgcYVFNfdAaQdVhLybs3WZF90OfcLlHZhVbAD2t9riclLGffQV0Gr6oDanfaLVlatQT%2fMfXtqg1YYomttxso2%2f8sWLkexliVOQfqXNZ9tF%2b37jh3HKcmLh5faOYZI2RZ565mxLd0JCU264%2btVd8BPNDCKaAgdSCHyn4dc4XSaoTs03sZ17L8h2S0tZ6lIhdhf%2bdPYOziOx5DQjaWQjX4NK7lv0rVfSH%2b08xdFxacE3vnp0MGUgU0ymRlviHuEFw6yJKFx0kE4x2PPpIAF909AfnQ09kUR8wyLKh3VqPdGkgXmeHElmjTBbo532yxbTQXtrAZa7NDoja%2brsu%2b3B7p9VzsNyxm7yETtvQiPbbViN86xHtrS%2fribpx&amp;vet=760&amp;dt=021018&amp;mlid=10273546429&amp;tmpID=3378&amp;linkname=InviteLink&amp;pt=0&amp;esp=0&amp;eaid=62798260&amp;rt=1

Secure your free coins &#9658;

Note: Unclaimed coins will be auctioned off to the rest of the community. (As an early member, you get exclusive first access to bid on any unclaimed coins).

Once again, THANK YOU.
-Your friends at empowr.com

Your account was reserved for you in order to allocate your free coins, however you must agree to terms and validate before it can be utilized. By accessing your account via the links or buttons in this email, you're both validating your email and stipulating that you're 18 or older and are signing up having agreed with the product, terms and privacy policies.

At this moment, empowr can make no guarantees about the current or future price or value of the new empowr cryptocurrency coin, or that it will be ultimately tradeable on one or more public currency exchanges. By accepting your free founder coins, you acknowledge that this offer represents a gift that can be revoked if it is found to not be legal in your state, country or jurisdiction. Vesting and other details apply.

You are receiving this gift and email because you were an alpha user of the SMS.ac / FanBox / empowr project. You can unsubscribe here
#.

-->

New! Download the empowr mobile app:

&nbsp;

&nbsp;

*This promotional email was sent to reply@reply.github.com and may contain special notices or offers. To see current terms and conditions visit: FanBox Terms and Conditions. You can prevent future emails here.
FanBox - 611 K Street, Suite B411, San Diego, CA 92101, USA
